name: Deploy to Firebase

on:
  push:
    branches:
      - main # Garante que só roda na branch principal
    paths:
      - 'functions/**'      # Roda se a pasta functions for alterada
      - 'firebase.json'     # Roda se o firebase.json for alterado

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies for Functions
        # Entra na pasta functions, instala os pacotes e volta para a raiz
        run: cd functions && npm install

      - name: Deploy to Firebase
        # Executa o comando de deploy a partir da raiz do projeto
        run: npx firebase-tools deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }} --project dashboard-mercocamp-214f1 --force
