name: Deploy to Firebase

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - 'firebase.json' # Adicionado para acionar o deploy se este arquivo mudar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies in Functions Folder
        run: cd functions && npm install

      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }} --project dashboard-mercocamp-214f1 --force
